### ISSUE TITLE
Configuration and Setup

### ISSUE THREAD

**Issue by add30417** [giejay/nukiPyBridge#4]
Dear Giejay,

Thanks for maintaining this project. Honestly I have the issue now to setup at my raspberry. I recognized you are using docker, but besides of the 10 Steps out of the Readme file, I can't go ahead. 

Maybe, can you please add more step how someone, like me, setup this from scratch ?

Thanks in advanced
Daniel

**Comment by giejay** [comment]
The readme is a bit outdated. You can use this script to set it up: https://github.com/giejay/nukiPyBridge/blob/master/install-bluetooth-deps.sh

At what step are you stuck?

**Comment by add30417** [comment]
Thanks for your answer.

First of all, I used a RP 3 B+. I downloaded the latest version from Raspbian and wrote a new sd card.

I found out the MAC address of my nuki.

I followed the 10 steps from the Readme file.

But now what is the next step, I couldn't found the NaCl utility on my sd card.
And even what should I do with the files from the git Repository? Can I use a docker? Or should I used without docker?

Honestly, I guess isn't rocket sicence any more, but just the next steps and the best way would be very helpful.

But I'm thanksful to you, you are maintining this project.

**Comment by giejay** [comment]
Did you try to install it using the file I mentioned? After that, you should have a running supervised service on port 5000. You can browse to that port and checkout the methods to use in server.py.

**Comment by add30417** [comment]
Just doing at the moment.

First run, with the error:
./install-bluetooth-deps.sh: line 20: ./install-bluez.sh: No such file or directory
cp: cannot stat 'nuki-supervised.conf': No such file or directory

**Comment by giejay** [comment]
Did you clone the entire repo or just copied that file?

**Comment by add30417** [comment]
I see, I guessed it is a "web" installer. I'm doing again. --- I will do the testing in the next days.

**Comment by add30417** [comment]
Now, I installed everything.

Following modifciation  I did:
connect-example.py: changing macaddress of nuki
run.sh: changed with raspberry pi ip address
nuki.conf: changed with raspberry pi ip address

I used the pi user.

When I'm excuting the server.py, following message I will got back:

./connect-example.py
Starting BLE adapter...
Failed to restart bluetooth.service: Unit bluetooth.service failed to load properly: Bad message.
See system logs and 'systemctl status bluetooth.service' for details.
Init Nuki BLE connection...
Unable to connect, retrying..., retry count: 1
Starting BLE adapter...
Failed to restart bluetooth.service: Unit bluetooth.service failed to load properly: Bad message.
See system logs and 'systemctl status bluetooth.service' for details.
Init Nuki BLE connection...
Unable to connect, retrying..., retry count: 2
Starting BLE adapter...
Failed to restart bluetooth.service: Unit bluetooth.service failed to load properly: Bad message.
See system logs and 'systemctl status bluetooth.service' for details.
Init Nuki BLE connection...
Unable to connect, retrying..., retry count: 3
Nuki BLE connection established
Traceback (most recent call last):
  File "./connect-example.py", line 18, in <module>
    nuki.Nuki(nukiMacAddress).authenticateUser(myPublicKeyHex, myPrivateKeyHex, myID, myIDType, name)
  File "/home/pi/nuki/nuki.py", line 92, in authenticateUser
    pairingHandle = self.device.get_handle('a92ee101-5501-11e4-916c-0800200c9a66')
AttributeError: 'NoneType' object has no attribute 'get_handle'


Error of bluetooth.service:
 /lib/systemd/system/bluetooth.service:1: Invalid section header '[Unit] Description=Bluetooth service Documentation=man:bluetoothd(8) Co...

**Comment by giejay** [comment]
There is something wrong with your bluetooth.service file. Can you post the content?

**Comment by add30417** [comment]
cat /lib/systemd/system/bluetooth.service

[Unit] Description=Bluetooth service Documentation=man:bluetoothd(8) ConditionPathIsDirectory=/sys/class/bluetooth

[Service]
Type=dbus
BusName=org.bluez
ExecStart=/usr/local/libexec/bluetooth/bluetoothd
NotifyAccess=main
#WatchdogSec=10
#Restart=on-failure
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
LimitNPROC=1
ProtectHome=true
ProtectSystem=full

[Install]
WantedBy=bluetooth.target
Alias=dbus-org.bluez.service

**Comment by giejay** [comment]
Please put a line break between [Unit] and Description

**Comment by add30417** [comment]
Seems like step ahead:

During the excution of "./connect-example.py" following output appears:
Init Nuki BLE connection...
Unable to connect, retrying..., retry count: 1
Starting BLE adapter...
Init Nuki BLE connection...
Unable to connect, retrying..., retry count: 2
Starting BLE adapter...
Init Nuki BLE connection...
Nuki BLE connection established
Nuki Pairing UUID handle created: 008b
Requesting Nuki Public Key using command: Nuki_REQ
        Payload: Nuki_PUBLIC_KEY
Nuki Public key requested
Nuki returned unexpected response (expecting PUBLIC_KEY): Nuki_ERROR
        Error Code: 10
        Command Identifier: 0001


During second and third execution, following output appears:
Starting BLE adapter...
Init Nuki BLE connection...
Unable to connect, retrying..., retry count: 1
Starting BLE adapter...
Init Nuki BLE connection...
Unable to connect, retrying..., retry count: 2
Starting BLE adapter...
Init Nuki BLE connection...
Unable to connect, retrying..., retry count: 3
Nuki BLE connection established
Traceback (most recent call last):
  File "./connect-example.py", line 18, in <module>
    nuki.Nuki(nukiMacAddress).authenticateUser(myPublicKeyHex, myPrivateKeyHex, myID, myIDType, name)
  File "/home/pi/nuki/nuki.py", line 92, in authenticateUser
    pairingHandle = self.device.get_handle('a92xxxxxxxxxxxxxxxxxxxxxxxxxx')
AttributeError: 'NoneType' object has no attribute 'get_handle'

**Comment by giejay** [comment]
Did you start the pairing process on your Nuki by holding it for 5 seconds?

**Comment by add30417** [comment]
Yes, I did.

Update:
Even the config file (/home/pi/nuki/nuki.cfg) never created during the execution. I created (with touch command) a empty file, but no success.

**Comment by add30417** [comment]
The following id is hard coded, is this right? a92ee202-5501-11e4-916c-0800200c9a66

How can I check the ID on my device? Or is it fixed?

**Comment by giejay** [comment]
Can you try it by using the connect endpoint? See server.py for the details

**Comment by add30417** [comment]
Bascially the server.py isn't helpful me. Is it? I can't see any helpful information.

**Comment by giejay** [comment]
It mentions the exact methods you can use for connecting and unlocking. For example: @app.route("/connect/<mac_address>/<name>")

So go to localhost:5000/connect/macaddress/frontdoor and it will try to pair

**Comment by add30417** [comment]
the server isn't working at my raspberry

**Comment by giejay** [comment]
Are you running it using the supervised service? What does 'sudo supervisorctl status nuki' give you?

**Comment by add30417** [comment]
# sudo supervisorctl status nuki
nuki                             FATAL     can't find command '/usr/local/bin/flask'

Seems not.

**Comment by giejay** [comment]
The install bluetooth deps script should have installed flask...

**Comment by add30417** [comment]
It is located in /usr/local/, I changed the config file

**Comment by add30417** [comment]
When I execute the server.py, I got the same error message back.

172.17.0.50 - - [14/Sep/2020 21:19:55] "GET /favicon.ico HTTP/1.1" 404 -
[2020-09-14 21:20:27,854] ERROR in app: Exception on /connect/xxxxxxx/FrontDoor [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/nuki/server.py", line 40, in connect
    nuki.Nuki(mac_address).authenticateUser(myPublicKeyHex, myPrivateKeyHex, myID, myIDType, name)
  File "/home/pi/nuki/nuki.py", line 92, in authenticateUser
    pairingHandle = self.device.get_handle('a92ee101-5501-11e4-916c-0800200c9a66')
AttributeError: 'NoneType' object has no attribute 'get_handle'
172.17.0.50 - - [14/Sep/2020 21:20:27] "GET /connect/xxxxxxxxx/FrontDoor HTTP/1.1" 500 -
172.17.0.50 - - [14/Sep/2020 21:20:27] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by giejay** [comment]
Are you using a nuki v2?

**Comment by add30417** [comment]
Yes, I'm using v2

**Comment by giejay** [comment]
Can you add --experimental to: ExecStart=/usr/local/libexec/bluetooth/bluetoothd.

What version are you using of bluez?

**Comment by add30417** [comment]
I got following log:

Sep 14 22:05:22 rasppi bluetoothd[2448]: Endpoint registered: sender=:1.43 path=/org/bluez/hci0/A2DP/SBC/Source/1
Sep 14 22:05:22 rasppi bluetoothd[2448]: Endpoint registered: sender=:1.43 path=/org/bluez/hci0/A2DP/SBC/Source/2
Sep 14 22:05:22 rasppi kernel: [  176.998435] debugfs: File 'le_min_key_size' in directory 'hci0' already present!
Sep 14 22:05:22 rasppi kernel: [  176.998459] debugfs: File 'le_max_key_size' in directory 'hci0' already present!
Sep 14 22:05:31 rasppi systemd[1]: Stopping BluezALSA proxy...
Sep 14 22:05:31 rasppi bluetoothd[2448]: Endpoint unregistered: sender=:1.43 path=/org/bluez/hci0/A2DP/SBC/Source/1
Sep 14 22:05:31 rasppi bluetoothd[2448]: Endpoint unregistered: sender=:1.43 path=/org/bluez/hci0/A2DP/SBC/Source/2
Sep 14 22:05:31 rasppi systemd[1]: bluealsa.service: Succeeded.
Sep 14 22:05:31 rasppi systemd[1]: Stopped BluezALSA proxy.
Sep 14 22:05:31 rasppi bluetoothd[2448]: Terminating
Sep 14 22:05:31 rasppi systemd[1]: Stopping Bluetooth service...
Sep 14 22:05:31 rasppi bluetoothd[2448]: Stopping SDP server
Sep 14 22:05:31 rasppi bluetoothd[2448]: Exit
Sep 14 22:05:31 rasppi systemd[1]: bluetooth.service: Succeeded.
Sep 14 22:05:31 rasppi systemd[1]: Stopped Bluetooth service.
Sep 14 22:05:32 rasppi systemd[1]: Starting Bluetooth service...
Sep 14 22:05:32 rasppi bluetoothd[2597]: Bluetooth daemon 5.51
Sep 14 22:05:32 rasppi systemd[1]: Started Bluetooth service.
Sep 14 22:05:32 rasppi bluetoothd[2597]: Starting SDP server
Sep 14 22:05:32 rasppi bluetoothd[2597]: Bluetooth management interface 1.14 initialized
Sep 14 22:05:32 rasppi systemd[1]: Started BluezALSA proxy.
Sep 14 22:05:32 rasppi bluetoothd[2597]: Endpoint registered: sender=:1.45 path=/org/bluez/hci0/A2DP/SBC/Source/1
Sep 14 22:05:32 rasppi bluetoothd[2597]: Endpoint registered: sender=:1.45 path=/org/bluez/hci0/A2DP/SBC/Source/2
Sep 14 22:05:32 rasppi kernel: [  187.132985] debugfs: File 'le_min_key_size' in directory 'hci0' already present!
Sep 14 22:05:32 rasppi kernel: [  187.133011] debugfs: File 'le_max_key_size' in directory 'hci0' already present!
Sep 14 22:05:38 rasppi systemd[1]: Stopping BluezALSA proxy...
Sep 14 22:05:38 rasppi systemd[1]: bluealsa.service: Succeeded.
Sep 14 22:05:38 rasppi bluetoothd[2597]: Endpoint unregistered: sender=:1.45 path=/org/bluez/hci0/A2DP/SBC/Source/1
Sep 14 22:05:38 rasppi bluetoothd[2597]: Endpoint unregistered: sender=:1.45 path=/org/bluez/hci0/A2DP/SBC/Source/2
Sep 14 22:05:38 rasppi systemd[1]: Stopped BluezALSA proxy.
Sep 14 22:05:38 rasppi bluetoothd[2597]: Terminating
Sep 14 22:05:38 rasppi systemd[1]: Stopping Bluetooth service...
Sep 14 22:05:38 rasppi bluetoothd[2597]: Stopping SDP server
Sep 14 22:05:38 rasppi bluetoothd[2597]: Exit
Sep 14 22:05:38 rasppi systemd[1]: bluetooth.service: Succeeded.
Sep 14 22:05:38 rasppi systemd[1]: Stopped Bluetooth service.
Sep 14 22:05:38 rasppi systemd[1]: Starting Bluetooth service...
Sep 14 22:05:38 rasppi bluetoothd[2774]: Bluetooth daemon 5.51
Sep 14 22:05:38 rasppi systemd[1]: Started Bluetooth service.
Sep 14 22:05:38 rasppi bluetoothd[2774]: Starting SDP server
Sep 14 22:05:38 rasppi bluetoothd[2774]: Bluetooth management interface 1.14 initialized
Sep 14 22:05:38 rasppi systemd[1]: Started BluezALSA proxy.
Sep 14 22:05:38 rasppi kernel: [  193.211177] debugfs: File 'le_min_key_size' in directory 'hci0' already present!
Sep 14 22:05:38 rasppi kernel: [  193.211200] debugfs: File 'le_max_key_size' in directory 'hci0' already present!
Sep 14 22:05:40 rasppi bluetoothd[2774]: Endpoint registered: sender=:1.47 path=/org/bluez/hci0/A2DP/SBC/Source/1
Sep 14 22:05:40 rasppi bluetoothd[2774]: Endpoint registered: sender=:1.47 path=/org/bluez/hci0/A2DP/SBC/Source/2

**Comment by add30417** [comment]
bluez is already the newest version (5.50-1.2~deb10u1+rpt2).

**Comment by add30417** [comment]
Any recommendation how I can fix this topic?

Thanks in advanced.

**Comment by giejay** [comment]
Something is stopping your Bluez service and I'm not sure what. Before doing anything with the lock, you have to make sure you have a stable bluetooth service. 

Do you only see those logs when interacting with the lock or are the logs always visible?

**Comment by NopfatGithub** [comment]
https://learn.adafruit.com/install-bluez-on-the-raspberry-pi/installation

Blues should work out of the box. Maybe check in the raspberry installation menu : raspi-config

Maybe restart the raspberry : sudo reboot

Does :  hcitool lescan      show devices? 

Try step 2 from this tutorial: https://github.com/tobiasfeistmantl/python-nuki-client

Did you copy the gattool to  path : ... Pyhton3.7 ....

Btw: thank you @giejay !

**Comment by add30417** [comment]
Thanks @giejay and @NopfatGithub  for your comments.

I tried with a second PI (PI 4) with fresh installation but also not working. Bluetooth in general is working and stable, tested with headset and a LEGO smart hub.

hcitool shows me around 10 devices, including my Nuki. 

Yes, I copied the gatttool.py in the right folder. And I'm using python3.7 for execution of the scripts. 

But the same results as before.

**Comment by giejay** [comment]
I'm gonna try a brand new install tomorrow on a raspberry pi and I'll see if I run into the same issues as you.

**Comment by add30417** [comment]
@giejay, Thanks looking forward to your feedback.

**Comment by giejay** [comment]
I have updated the repo and added retry mechanism (to improve stability and speed) and updated the Readme. Also added logging to get some more insights into your problem. Can you try again?

**Comment by add30417** [comment]
Thanks for your feedback. I tried it again.

One issue, I could fixed:
cp: cannot create regular file '/usr/local/lib/python3.6/dist-packages/pygatt/backends/gatttool/gatttool.py': No such file or directory

For the second one, I don't have any experiences:
pi@rasp: /home/pi/nukiPyBridge# sudo supervisorctl start nuki
nuki: ERROR (no such file)

Do you have any advice for me?

**Comment by giejay** [comment]
Where does your python install the packages? What version do you have? Can you do an "ls /usr/local/lib"? 

Because that step failed, the step after that also fails:

sudo cp nuki-supervised.conf /etc/supervisor/conf.d/nuki.conf

You can do this manually and then do a start nuki again.

**Comment by add30417** [comment]
Ls output: cups  pypy2.7  python2.7  python3.7

I did "sudo cp nuki-supervised.conf /etc/supervisor/conf.d/nuki.conf" already before.

**Comment by giejay** [comment]
Can you try a sudo supervisorctl reread and a "sudo supervisorctl update"?

And this should be the step for the gatttool copy:

```
sudo cp gatttool.py /usr/local/lib/python3.7/dist-packages/pygatt/backends/gatttool/gatttool.py
```

**Comment by add30417** [comment]
The copy command was ok. But I updated the nuki.conf file:
[program:nuki]

command=**/usr/bin/flask** run -h **172.17.0.70**  #I updated the path information and IP address
environment=FLASK_APP="server.py",PYTHONUNBUFFERED=true
directory=**/home/pi/nukiPyBridge/** #I updated the path information
redirect_stderr=true
startsecs=5
autorestart=true
itdout_logfile=/home/pi/nukiPyBridge/server.log #I updated the path information


The server is starting now, but I can't access from my PC.

**Comment by add30417** [comment]
I also updated the run.sh:
#cd /home/pi/nukiPyBridge
export FLASK_APP=server.py
flask run -h 172.17.0.70 -p 10000

**Comment by add30417** [comment]
I moved to /home/pi/nuki everything and updated the all above mention path.

But same results again.

But I found out, no server.log is created.

**Comment by giejay** [comment]
Can you do a 

sudo supervisorctl tail nuki

**Comment by giejay** [comment]
You probably also need

pip3 install retry

**Comment by add30417** [comment]
root@raspberrypi:/home/pi/nuki# pip3 install retry
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: retry in /usr/local/lib/python3.7/dist-packages (0.9.2)
Requirement already satisfied: py<2.0.0,>=1.4.26 in /usr/local/lib/python3.7/dist-packages (from retry) (1.9.0)
Requirement already satisfied: decorator>=3.4.2 in /usr/local/lib/python3.7/dist-packages (from retry) (4.4.2)

**Comment by giejay** [comment]
And the tail command?

**Comment by add30417** [comment]
right


/home/pi/nuki# sudo supervisorctl tail nuki
 * Serving Flask app "server.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
{}
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Serving Flask app "server.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
{}
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)


If I using http://172.17.0.70:5000/connect/54:ddddedsd/frontdoor follow update is comming:
Connected to 54: ddddedsd

But still no server log.

**Comment by add30417** [comment]
If I'm using **http://172.17.0.70:5000/frontdoor/lock** or **unlock** following message is coming:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by giejay** [comment]
If you do

sudo supervisorctl tail -f nuki

And then call the lock endpoint, you don't see any logs?

**Comment by add30417** [comment]
sudo supervisorctl tail -f nuki
==> Press Ctrl-C to exit <==
ckages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/nuki/server.py", line 45, in lock_door
    return execute_action('LOCK', door)
  File "/home/pi/nuki/server.py", line 64, in execute_action
    nuki.Nuki(config[door]).lockAction(type)
KeyError: 'frontdoor'
INFO:werkzeug:172.17.0.50 - - [07/Oct/2020 20:24:48] "GET /frontdoor/lock HTTP/1.1" 500 -

**Comment by giejay** [comment]
Ah yes. That's still a bug, you need to restart after connecting a new lock.

sudo supervisorctl restart nuki

**Comment by add30417** [comment]
Even after restart of the Rasp following message occur:

INFO:werkzeug:172.17.0.50 - - [07/Oct/2020 20:36:54] "GET /frontdoor/lock HTTP/1.1" 500 -
ERROR:flask.app:Exception on /frontdoor/lock [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/nuki/server.py", line 45, in lock_door
    return execute_action('LOCK', door)
  File "/home/pi/nuki/server.py", line 64, in execute_action
    nuki.Nuki(config[door]).lockAction(type)
KeyError: 'frontdoor'
INFO:werkzeug:172.17.0.50 - - [07/Oct/2020 20:37:47] "GET /frontdoor/lock HTTP/1.1" 500 -

**Comment by giejay** [comment]
Can you post the contents of your nuki.cfg? It should be created in the home/pi/nuki folder

**Comment by add30417** [comment]
Sorry I coundn't found any nuki.cfg

Even I searched with **sudo find /-name nuki.cfg**

**Comment by giejay** [comment]
Then I guess that's the problem. Are you sure the connect went ok? Can you try again and verify the existence of nuki.cfg?

**Comment by add30417** [comment]
How can I check it (connect went ok)?

**Comment by add30417** [comment]
I guess, connected didn't went ok:

/home/pi/nuki# sudo supervisorctl tail -f nuki
==> Press Ctrl-C to exit <==
r...
INFO:pygatt.backends.gatttool.gatttool:Stopping
INFO:pygatt.backends.gatttool.gatttool:Listener thread finished
INFO:pygatt.backends.gatttool.gatttool:Running...
Init Nuki BLE connection...
INFO:pygatt.backends.gatttool.gatttool:Connecting to 54xxxxxwith timeout=5.0
ERROR:pygatt.backends.gatttool.gatttool:Timed out connecting to 54:xxxx after 5.0 seconds.
Unable to connect, retrying..., retry count: 2
Starting BLE adapter...
INFO:pygatt.backends.gatttool.gatttool:Stopping
INFO:pygatt.backends.gatttool.gatttool:Listener thread finished
INFO:pygatt.backends.gatttool.gatttool:Running...
Init Nuki BLE connection...
INFO:pygatt.backends.gatttool.gatttool:Connecting to 54:xxx with timeout=5.0
ERROR:pygatt.backends.gatttool.gatttool:Timed out connecting to 54:xxxx after 5.0 seconds.
Unable to connect, retrying..., retry count: 3
Could not connect after 3 tries
INFO:werkzeug:172.17.0.50 - - [07/Oct/2020 20:53:56] "GET /connect/54xxxxxx/frontdoor HTTP/1.1" 200 -
Starting BLE adapter...
Init Nuki BLE connection...
INFO:pygatt.backends.gatttool.gatttool:Running...
INFO:pygatt.backends.gatttool.gatttool:Connecting to 54:xxxx with timeout=5.0
ERROR:pygatt.backends.gatttool.gatttool:Timed out connecting to 54:xxxxxxxx after 5.0 seconds.
Unable to connect, retrying..., retry count: 1
Starting BLE adapter...
INFO:pygatt.backends.gatttool.gatttool:Stopping
INFO:pygatt.backends.gatttool.gatttool:Listener thread finished
INFO:pygatt.backends.gatttool.gatttool:Running...
Init Nuki BLE connection...
INFO:pygatt.backends.gatttool.gatttool:Connecting to 54:Dxxxxx with timeout=5.0
ERROR:pygatt.backends.gatttool.gatttool:Timed out connecting to 54xxxxxx after 5.0 seconds.
Unable to connect, retrying..., retry count: 2
Starting BLE adapter...
INFO:pygatt.backends.gatttool.gatttool:Stopping
INFO:pygatt.backends.gatttool.gatttool:Listener thread finished
INFO:pygatt.backends.gatttool.gatttool:Running...
Init Nuki BLE connection...
INFO:pygatt.backends.gatttool.gatttool:Connecting to 54:xxxxx with timeout=5.0
ERROR:pygatt.backends.gatttool.gatttool:Timed out connecting to 54xxxx after 5.0 seconds.
Unable to connect, retrying..., retry count: 3
Could not connect after 3 tries
INFO:werkzeug:172.17.0.50 - - [07/Oct/2020 20:54:29] "GET /connect/5xxxxx/frontdoor HTTP/1.1" 200 -

**Comment by giejay** [comment]
Is the lock in close proximity and in pairing mode?

I also made some modifications so you need to git pull to fetch the latests goodies.

**Comment by add30417** [comment]
it is close and in pairing mode. In addition, I checked the status inside the app. Pairing is allowed.

But no changes happen.

**Comment by giejay** [comment]
Do you see the device when scanning with hcitool scan?

**Comment by add30417** [comment]
Yes

hcitool lescan
LE Scan ...
54:xxxxxx (unknown)
54:xxxxxx Nuki_xxxxx

**Comment by giejay** [comment]
Hmm then I'm out of ideas... Seems your Bluetooth dongle is not happy with the locks

**Comment by add30417** [comment]
Well, isn’t dongle . It is the integrated BT chip of the rasp.

Can you make a trial-Function. Just pairing of the Nuki without any specific function/code around? Like a minicom?

**Comment by giejay** [comment]
That's exactly the way Im using it (raspberry pi 3).

The line of code which shows the error is the very first line of code, just to make the bluetooth connection. No Nuki specific code is being hit/used. 

Somehow, it won't connect to the lock and that's very weird, since you should be able to connect, even without entering the pairing mode (just tried, then the public key exchange fails, but connecting works fine!).

Can you try connecting with gatttool itself? 

```
sudo gatttool -b <mac address> --interactive
```
In the terminal type: connect

You should see:

```
sudo gatttool -b 54:D2:72:1A:XX:XX --interactive
[54:D2:72:1A:XX:XX][LE]> connect
Attempting to connect to 54:D2:72:1A:XX:XX
Connection successful
[54:D2:72:1A:XX:XX][LE]> 
```

**Comment by add30417** [comment]
Sorry for my late response:

I got following message: Error: connect error: Connection timed out (110)

**Comment by giejay** [comment]
Can you try a few times? I also saw some timeouts

**Comment by add30417** [comment]
I did now. 15 times failed. 16th was "successful":

LE]> 
(gatttool:1596): GLib-WARNING **: 19:51:39.847: Invalid file descriptor.

**Comment by NopfatGithub** [comment]
That is great support.

**Comment by giejay** [comment]
> I did now. 15 times failed. 16th was "successful":
> 
> LE]>
> (gatttool:1596): GLib-WARNING **: 19:51:39.847: Invalid file descriptor.

I don't see a connect message yet. As long as you are not seeing a connect message, this library won't work. In another repository I read that the internal Bluetooth adapter can be very unstable with regards to BLE devices. Can you try a dongle?

**Comment by giejay** [comment]
@add30417 I have created another forked repo with nuki bridge support: https://github.com/giejay/nubli

It works exactly the same (same endpoints) as this repo, with the added benefit that it does not require a lot of configuration. Just install node 12 (https://github.com/cncjs/cncjs/wiki/Setup-Guide:-Raspberry-Pi-%7C-Install-Node.js-via-Node-Version-Manager-(NVM)), run npm install and then run node dist/lib/server.js

That will boot up a server on port 8080 and you can pair and unlock:

http://localhost:8080/44:22:BB:CC:DD/pair/RearDoor.
http://localhost:8080/RearDoor/lock

Pairing works in a few seconds, and so does locking/unlocking!!

**Comment by add30417** [comment]
Thanks for the support @giejay . I still waiting for a new Bluetooth dongle (Should arrive at Wednesday/Thursday).

I will come back to you.

**Comment by add30417** [comment]
Great now is working. Thanks a lot.

I bought a bt stick.

**Comment by giejay** [comment]
Thanks for the feedback! What's your average response time for unlocking?

**Comment by add30417** [comment]
I really don't know. After setup the server with nubli, I discover it isn't very stable. After 5-6 commands, a restart is necessary. 

So i changed it to the single scripts from the example folder to lock/unlock my nuki. But then I discovered, it is good to restart the bluetooth interface with "hciconfig hci0" to have a stable execution of the function.

**Comment by giejay** [comment]
For me the nubli project is also very unstable. Also tried it by resetting hci0 through javascript but that didn't help. I'm going back to this project again. It's a bit slower but it's much more stable.

**Comment by add30417** [comment]
I see, but with hci0 restart I have a success rate of 100%. Timing isn't the best, but is ok. I will using the way only limited time.

**Maybe one remark:** I'm using python to restart hci0, with javascript wasn't possible due to system rights.

Now with this new BT dongle, I can try also this project, maybe next weekend.

**Comment by add30417** [comment]
@giejay: Now I understand what you mean. Sometimes I have also the effect, the connection to Nuki isn't possible. Even the hciconfig hci0 isn't helpful. Only after unplugging of the Dongle or a restart of the pi, solve the issue.

Did you tried follow sequence?
hciconfig hci0 down
hciconfig hci0 reset
node getLockState.js

**Comment by farecious** [comment]
Hi Guys,

Would you recommend this project for a beginner?
I don't have much experience and knowledge with raspberry, haven't done more than just setting up a magicmirror and vpn server. Currently, I use an old Android-phone with the Software Bridge-app. But had also a Rpi2+ laying arround wanted to know if it's possible use that as my PyBridge and if its not to advanced for a beginnen?

Looking forward hearing from you guys!

**Comment by vin-d** [comment]
I Also get. 
`AttributeError: 'NoneType' object has no attribute 'get_handle'`. 
and I'm using the docker-compose version on a pi v4 with the regular bluetooth on it.

Anybody had luck with the regular bluetooth and a pi v4 ? should my only option be to buy a dongle ? if the Pi's bluetooth isn't right how can I know if the dongle I'll buy will work better ? :-/
