### ISSUE TITLE
Connect won't work anymore

### ISSUE THREAD

**Issue by Pingbo** [giejay/nukiPyBridge#6]
Hi,

seems the connect is also not working anymore :(
Getting the following issue every time:

Starting BLE adapter...
Stopping bluetooth: /usr/sbin/bluetoothd.
Starting bluetooth: bluetoothd.
INFO:pygatt.backends.gatttool.gatttool:Running...
Init Nuki BLE connection...
INFO:pygatt.backends.gatttool.gatttool:Connecting with timeout=5.0
Nuki BLE connection established
Nuki Pairing UUID handle created: 008b
INFO:pygatt.backends.gatttool.gatttool:Sent cmd=char-write-req 0x8c 0200
INFO:pygatt.device:Subscribed to uuid=a92ee101-5501-11e4-916c-0800200c9a66
INFO:pygatt.device:Received notification on handle=0x8b, value=0xb'0300f57424c4889630d4df054dce3d32956a2d3a'
INFO:pygatt.device:Received notification on handle=0x8b, value=0xb'241c221dc867c7801e0e51a83546490d'
Requesting Nuki Public Key using command: Nuki_REQ
        Payload: Nuki_PUBLIC_KEY
INFO:pygatt.backends.gatttool.gatttool:Sent cmd=char-write-req 0x8b 0100030027a7
Nuki Public key requested
Public key received: f57424c4889630d4df054dce3d32956a2d3a241c221dc867c7801e0e51a83546
Pushing Public Key using command: Nuki_PUBLIC_KEY
        Key: 1350307625edc9b91814a944aff2efcee0361bcf417bd43ee91eddbadca9ba17
INFO:pygatt.device:Received notification on handle=0x8b, value=0xb'0400156e2b520c773736bd683a1e9a3af87ffcac'
INFO:pygatt.device:Received notification on handle=0x8b, value=0xb'f340281f72292d3460d1558a14b86c07'
Public key pushed
INFO:pygatt.backends.gatttool.gatttool:Sent cmd=char-write-req 0x8b 03001350307625edc9b91814a944aff2efcee0361bcf417bd43ee91eddbadca9ba17934c
Challenge received: 156e2b520c773736bd683a1e9a3af87ffcacf340281f72292d3460d1558a14b8
INFO:pygatt.device:Received notification on handle=0x8b, value=0xb'0400b65867db675dee5464a13984e9089bb7bd5f'
INFO:pygatt.device:Received notification on handle=0x8b, value=0xb'684d86a494bc4af83b7d73c1bfc6d0b1'
INFO:pygatt.backends.gatttool.gatttool:Sent cmd=char-write-req 0x8b 05009d07d0c3b3ce567aa1136f53105ca3bdffe1c76b163210f42569f6da1c921a706902
Authorization Authenticator sent: Nuki_AUTH_AUTHENTICATOR
        Authenticator: 9d07d0c3b3ce567aa1136f53105ca3bdffe1c76b163210f42569f6da1c921a70
Challenge received: b65867db675dee5464a13984e9089bb7bd5f684d86a494bc4af83b7d73c1bfc6
ERROR:pygatt.backends.gatttool.gatttool:No response received
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 427, in char_write_handle
    self._receiver.wait("char_written", timeout=5)
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 129, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None
192.168.2.210 - - [14/Oct/2020 09:23:20] "GET /connect/54:D2:72:0E:72:C5/Zuhause HTTP/1.1" 500 -
INFO:werkzeug:192.168.2.210 - - [14/Oct/2020 09:23:20] "GET /connect/54:D2:72:0E:72:C5/Zuhause HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nuki/server.py", line 46, in connect
    nuki.Nuki(mac_address, configfile).authenticateUser(myPublicKeyHex, myPrivateKeyHex, myID, myIDType, name)
  File "/opt/nuki/nuki.py", line 150, in authenticateUser
    self.device.char_write_handle(pairingHandle, authDataCommand, True, 7)
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/device.py", line 17, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/device.py", line 48, in char_write_handle
    self._backend.char_write_handle(self, handle, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 427, in char_write_handle
    self._receiver.wait("char_written", timeout=5)
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 129, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None

**Comment by Pingbo** [comment]
Working again, after restarting nuki itself
