### ISSUE TITLE
docker Problem

### ISSUE THREAD

**Issue by Hagenmue** [giejay/nukiPyBridge#7]
Mit der Originaldatei "docker-compose.yml" ist kein Pairing möglich. Fehlermeldung: "... ist ein Verzeichnis"
Habe das Verzeichnis nuki.cfg gelöscht und im Stammverzeichnis eine leere Datei "nuki.cfg" angelegt.
Das *yml File wie folgt geändert:
`....
volumes:
          - ./nuki.cfg:/opt/nuki/nuki.cfg
.... 
`
Nun war Pairing möglich. Alle anderen Aufrufe führen aber weiterhin zu Fehlern, wie z.B.:
` ....
nit Nuki BLE connection...
nuki_1  | INFO:pygatt.backends.gatttool.gatttool:Connecting with timeout=5.0
nuki_1  | Nuki BLE connection established
nuki_1  | INFO:pygatt.backends.gatttool.gatttool:Sent cmd=char-write-req 0x93 0200
nuki_1  | INFO:pygatt.device:Subscribed to uuid=a92ee202-5501-11e4-916c-0800200c9a66
nuki_1  | ERROR:pygatt.backends.gatttool.gatttool:No response received
nuki_1  | Traceback (most recent call last):
nuki_1  |   File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 427, in char_write_handle
nuki_1  |     self._receiver.wait("char_written", timeout=5)
nuki_1  |   File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 129, in wait
nuki_1  |     raise NotificationTimeout()
nuki_1  | pygatt.exceptions.NotificationTimeout: None
....
`

**Comment by pberthold** [comment]
I also had this initial issue with Docker, but it was sufficient to remove the folder and create the file as you did. It seems the other errors are independent from that?
